name: HoloGUIApiExamplePlugin
main: com.antarescraft.kloudy.hologuiapi.exampleplugin.ExamplePlugin
version: 1.0.2
author: Kloudy
website: www.antarescraft.com

depend: [HoloGUIApi]

commands:
  stopwatch:
    description: used to define commands for the HoloGUIApiExample plugin